# @format
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.metadata.name }}-service"
spec:
  selector:
    app: "{{ .Values.metadata.name }}" # Select pods with this label
  ports:
    - protocol: TCP
      port: 80 # Port exposed outside the cluster
      targetPort: 3000 # Port that the Next.js app listens to in the container
  type: LoadBalancer # You can use NodePort or ClusterIP depending on your setup
